feat: created routes to upload image to ocr
GDGVIT/vitty-backend pull request #3
Opened 2021-04-08 15:38 UTC by VisheshBansal

2021-04-08 17:38 UTC, VisheshBansal commented
@SaurusXI Pls review

2021-04-09 07:05 UTC, SaurusXI requested changes

2021-04-09 07:05 UTC, SaurusXI commented on tableDetection.py
> +        cv2.drawContours(image, [c], -1, (36, 255, 12), 2)
Put redundant code from here in a separate function, call each time for drawing horizontal/vertical contours

2021-04-09 07:05 UTC, SaurusXI commented on main.py
> +from fastapi import FastAPI, File, UploadFile
Sort imports

2021-04-09 13:28 UTC, SaurusXI approved these changes

2021-04-09 13:31 UTC, SaurusXI commented
@VisheshBansal feedback on commit messages - if you're making a commit to fix linting issues, don't make a separate commit for it as it doesn't signify a new/different state of your project. Instead, use rebasing to make linting fixes in the same commit.
More specifically, all 5 of your latest commits should have been squashed into a single commit.

2021-04-09 13:31 UTC, merged

2021-04-09 13:38 UTC, VisheshBansal commented
> @VisheshBansal feedback on commit messages - if you're making a commit to fix linting issues, don't make a separate commit for it as it doesn't signify a new/different state of your project. Instead, use rebasing to make linting fixes in the same commit.
> More specifically, all 5 of your latest commits should have been squashed into a single commit.

Sure will keep it in mind. Thanks alot!